version: "3.4"

services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/minio/data:/data
      - /root/minio/config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio
    command: server --console-address ':9001' /data
    restart: always
  thumbor:
    container_name: thumbor
    image: minimalcompact/thumbor
    ports:
      - 8999:80
    restart: always